### ISSUE TITLE
nubia的ota7.1与6.0路径不同怎么改让它同时兼容6.0和7.1ota呢？

### ISSUE THREAD

**Issue by youyim** [cofface/android_bootable_recovery-twrp#6]
6.0路径 "/data/dm/delta/system.delta";
7.1路径"/data/data/cn.nubia.systemupdate/files/delta/system.delta";

**Comment by cofface** [comment]
你有没有机器测试？有开发者提交了个更新，你合并测试下？https://github.com/cofface/android_bootable_recovery-twrp/pull/5/commits/2b173a79aa51c1798b6b91dd4696db5ad1483916

**Comment by youyim** [comment]
@cofface 我测试了一下他的提交，再7.1（"/data/data/cn.nubia.systemupdate/files/delta/system.delta"）上ota正常，可是6.0（ "/data/dm/delta/system.delta"）上ota时重启到rec后不会刷入system.delta

**Comment by cofface** [comment]
有没有社交账号联系？如QQ。

**Comment by youyim** [comment]
@cofface QQ974627221

**Comment by cofface** [comment]
https://github.com/cofface/android_bootable_recovery-twrp/commit/b45c215ce23b6ac42d74a8468182dee6e1385c1a

更新我这个提交试试
